function adjustpath_inittable(hFig)
h = getappdata(hFig,'handles');
pathLabels = getappdata(hFig,'pathLabels');
colNames = {'Maze','Location','Width','Height','Show'};
colFmt = {{'Figure 8'},{'1','2','New location...'},'numeric','numeric','logical'};
defData = repmat({'Figure 8', '1',100,100',true},length(pathLabels),1);

h.pathTable = uitable('Parent',h.pathPanel,...
                    'Data',defData,...
                    'ColumnName', colNames,...
                    'ColumnFormat',colFmt,...
                    'ColumnEditable',[true true false false],...
                    'ColumnWidth',{'auto',50,45 45,45},...
                    'RowName',pathLabels);
setappdata(hFig,'handles',h);
