function hFig = adjustpathbatch_create(batchAdj,sessInfo,toDef)
figTitle = ['Adjust path - ' batchAdj.adjFile];
hFig = figure(...
	'Visible','on',... 
    'Position',[490 210 1200 780],...
    'Name',figTitle,...
    'Resize','off',...
    'MenuBar','None',...
    'NumberTitle','off',...
    'Color',[0 0.2 0.5],...
    'CreateFcn',@adjustpathbatch_initlayout,...
    'CloseRequestFcn',@adjustpathbatch_quit);
drawnow;
adjustpath_initadjtable(hFig);
adjustpathbatch_initguidata(batchAdj,sessInfo,toDef,hFig);
adjustpath_initpathtable(hFig);
% adjustpath_initreftable(hFig);
adjustpathbatch_initdisplay(hFig);
