function adjustpath_initadjtable(hFig)
h = getappdata(hFig,'handles');
colNames = {'x Center','y Center','x Scale','y Scale'};
colFmt = {'numeric','numeric','numeric','numeric'};
defData = {0,0,0,0};

h.adjTable = uitable('Parent',h.adjTablePanel,...
                    'Data',defData,...
                    'ColumnName', colNames,...
                    'ColumnFormat',colFmt,...
                    'ColumnEditable',[false false false false],...
                    'ColumnWidth',{'auto','auto','auto' 'auto'},...
                    'RowName',[]);
setappdata(hFig,'handles',h);
