function hFig = adjustpath_create(pathDirs)
hFig = figure(...
	'Visible','on',... 
    'Position',[490 210 1200 780],...
    'Name','Adjust Path',...
    'Resize','off',...
    'MenuBar','None',...
    'NumberTitle','off',...
    'Color',[0 0.2 0.5],...
    'CreateFcn',@adjustpath_initlayout);
drawnow;
adjustpath_initguidata(pathDirs,hFig);
adjustpath_initpathtable(hFig);
adjustpath_initadjtable(hFig);
% adjustpath_initreftable(hFig);
adjustpath_initdisplay(hFig);
