function adjustpath_initpathtable(hFig)
h = getappdata(hFig,'handles');
% pathLabels = getappdata(hFig,'pathLabels');
colNames = {'Maze','Location','Width','Height','Show'};
defMazes = defmazes();
mazeNames = {defMazes.name};
colFmt = {mazeNames,{'1','New location...'},'numeric','numeric','logical'};
% defData = repmat({'-', '1','-','-',true},length(pathLabels),1);

h.pathTable = uitable('Parent',h.pathPanel,...
                    'Data',{},...
                    'ColumnName', colNames,...
                    'ColumnFormat',colFmt,...
                    'ColumnEditable',[true true false false true],...
                    'ColumnWidth',{'auto',50,45 45,45},...
                    'RowName',[],...
                    'CellEditCallback',{@adjustpath_editpathtable,hFig});
setappdata(hFig,'handles',h);
