function toApp = appbatch_create(adj)
hFig = figure(...
	'Visible','on',... 
    'Position',[490 210 800 400],...
    'Name','Select adjustments to apply',...
    'Resize','off',...
    'MenuBar','None',...
    'NumberTitle','off',...
    'Color',[0 0.2 0.5],...
    'CreateFcn',@appbatch_initlayout);
setappdata(hFig,'adj',adj);
appbatch_settabledata(hFig);
uiwait(hFig);
toApp = getappdata(hFig,'toApp');
delete(hFig);
