function toDef = defbatch_create(adj)
hFig = figure(...
	'Visible','on',... 
    'Position',[490 210 800 400],...
    'Name','Select adjustments to define',...
    'Resize','off',...
    'MenuBar','None',...
    'NumberTitle','off',...
    'Color',[0 0.2 0.5],...
    'CreateFcn',@defbatch_initlayout);
setappdata(hFig,'adj',adj);
defbatch_settabledata(hFig);
uiwait(hFig);
toDef = getappdata(hFig,'toDef');
delete(hFig);
