function hTable = initdeftable(hParent)
colNames = {'Session','Defined','Definition date','Applied','Application date','Define'};
colFmt = {'char','char','char','char','char','logical'};
colEditable = [false, false, false, false, false,true];
colWid = {'auto','auto',150,'auto',150,'auto','auto'};
rowNames = [];
hTable = uitable('Parent',hParent,...
                    'ColumnName',colNames,...
                    'ColumnFormat',colFmt,...
                    'ColumnEditable',colEditable,...
                    'ColumnWidth',colWid,...
                    'RowName',rowNames);